### ISSUE TITLE
CPU usage spikes regularly, with incremental increases in spike frequency.

### ISSUE THREAD

**Issue by Allunderheaven** [Stonebound/principium#6]
#### Reproduction Steps: Play Principium Multiplayer for ~30 minutes.

After ten to twenty minutes of Multiplayer gameplay, Minecraft will begin to stutter in conjunction with CPU load increasing to %90-100 ranges. The issue persists for the remainder of the session, increasing in frequency the longer one plays. Spike times logged from last session attempted:
- First spike at 12:36 playtime.
- 15:11
- 18:30
- 20:00
- 22:00
- 23:30
- 24:30
- 25:00
- 25:30
- 26:00

Spikes continue indefinitely roughly every ten(10) seconds from there out.

This issue presented across three different computers.

**Comment by monkeybug34** [comment]
Same situation on my computer, along with Ovralyne's.
I diddnt seem to have the problem though while I played on a singleplayer world for several hours while I was waiting for my whitelist application to go through.
Perhaps we can get a test server without any plugins going and see if the problem persists?

**Comment by phit** [comment]
there are no plugins on the server

could you please look at this and run it next time you play, http://ae-mod.info/profiling/
the post the resulting file here, thanks!

**Comment by phit** [comment]
caused by the vanilla launcher that Curse uses, just kill the launcher once your game starts
not sure what exactly triggers it, doesn't seem to happen all the time

**Comment by monkeybug34** [comment]
it also happens when running with the technic launcher

**Comment by phit** [comment]
then do this, I don't have the problem myself at all so it's hard to troubleshoot for me

> could you please look at this and run it next time you play, http://ae-mod.info/profiling/
> the post the resulting file here, thanks!
