### ISSUE TITLE
Clientside Crash when viewing inventory

### ISSUE THREAD

**Issue by ArbitraryHubris** [Stonebound/principium#7]
#### Modpack Version:

1.0.7
#### Reproduction Steps:

Every time I hit E to open inventory I crash
#### Logs:

http://pastebin.com/LXcvuTr3

I'm going to try a newer version of JEI and see if that helps.  I have no idea why this started happening.  I've been playing all morning with no trouble and now I can't view my inventory.

**Comment by phit** [comment]
https://github.com/squeek502/AppleCore/issues/70

**Comment by phit** [comment]
fixed in 1.0.8
